### ISSUE TITLE
adding sound

### ISSUE THREAD

**Issue by DanielRuf** [benbyford/stopmotion-lite.js#1]
Would be great if you could something like soundmanager 2, html5 audio ... with modernizr.js so we could convert theoretically a full movie to js / html5?

Sound as mp3 and ogg works everywhere but there are too many different html5 video formats and it doesnt work in every browser

Often we have to use a flash fallback

**Comment by benbyford** [comment]
Sounds insteresting, ill look into it, but i can already see a majpr problem being the synching issue.

**Comment by DanielRuf** [comment]
hm, saw many examples for the audio api and how to control it with javascript, soundmanager2 should be right, has many features and preloading should be possible

**Comment by benbyford** [comment]
Just checked it out, looks great, will look to include it in the next version - I'll keep you posted.

**Comment by DanielRuf** [comment]
ok thats great =) think its very easy to include this  if you need help with it just let me know

**Comment by benbyford** [comment]
Hey - been looking into the audio side of things. 

With soundmanager2 and other sound solutions they provide a flash fall back and have (in my opinion) made the solution complex and annoying to impliment.

Soooo, as the stopmotion-lite.js plugin is ment to be as lite weight as possible I'm looking to impliment a html5, and an object solution for html4/xhtml compatible browsers with a video fallback (i.e. put your video link here if nothing works, letting vimeo / youtube etc do the fall).

If your interested in forking and having a go with soundmanager be my guest.

But will let you know how it goes, and let me know if you have any more requests etc..

**Comment by DanielRuf** [comment]
ok, i will do some experiments with soundmanager2 and the audio api / javascript
wellyou mean you want to add videos as feature?

currently im working on an improved version for creating movies for stopmotion-lite and also process them, store them a(and also save huge amount of space) and create a backend for managing the videos
